backend:
  name: github
  repo: BigBeatz/myblog
  branch: main
  base_url: "https://decap-oauth-worker.linbie999.workers.dev"
  auth_endpoint: "auth"
  site_domain: "blog.biglbeatz.ggff.net"
  open_authoring: false

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "正文", name: "body", widget: "markdown"}
